# Generated by Django 5.0.3 on 2024-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
